# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02f418269e2d9dfe2514d133a17976469ce7c2b1c241fe69c80908314b17bd0330baa6f94162f12d2757d2bdc01d9405f060f216b839fd5be7b51fd418b3acbb

test:
  secret_key_base: 8250d30f8c7965a82f05a400a0b89167b232e1b4b1ed9c1eda0870cafa083892446e182cbd48b834cd9c1465e56704faa4bbc44c4218c20d7f371cc886785f00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
